jobs:
  first_job:
    name: 'First Job'

    runs-on: ubuntu-latest 

    steps:
      - name: Sqy Hello from First Job
        shell: bash
        run: |
          echo "Hello World"

  second_job: 
    name: 'Second Job'

    runs-on: ubuntu-latest 

    steps:
      - name: Sqy Hello from Second Job
        shell: bash
        run: |
          echo "Hello World"