# main.yaml
name: 'My First GitHub Actions'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call_build:
    uses: ./.github/workflows/ci.yaml
    with:
      artifact_name: apiapp