name: 'My First GitHub Actions'

on: push 

jobs:
  call_build:
    uses: ./.github/workflows/ci.yaml
    with:
      artifact_name: apiapp
  
  call_release:
    uses: ./.github/workflows/cd.yaml
    with:
      title: ${{ github.event.inputs.title }}
      artifact_name: api_app
    secrets: inherit
  