# manual-release.yml
name: 'Manual Release'

on:
  workflow_dispatch:
    inputs:
      title:
        type: string
        required: true
        description: Title of release

jobs:
  call_build:
    uses: ./.github/workflows/ci.yaml
		needs: call_build
    with:
      artifact_name: apiapp

  call_release:
    uses: ./.github/workflows/cd.yaml
		needs: call_build
    with:
      title: ${{ github.event.inputs.title }}
      artifact_name: apiapp
    secrets: inherit